language: go

go:
  - 1.x
  - master

matrix:
  allow_failures:
    - go: master

install:
  - go get github.com/mattn/goveralls
  - go get github.com/golang/lint/golint
  - go get github.com/golang/dep/cmd/dep
  - dep ensure
before_script:
  - test -z "$(gofmt -s -l . 2>&1 | grep -v vendor | tee /dev/stderr)"
  - golint -set_exit_status $(go list ./...)
script:
  - go test -coverprofile=coverage.out -race -vet all ./pkg/...
after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci

services:
  - docker
